# Generated by Django 5.0.2 on 2025-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(blank=True, choices=[('language', 'Lenguaje'), ('framework', 'Framework'), ('software', 'Software'), ('tool', 'Herramienta'), ('library', 'Librería'), ('other', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/certificates'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/technologies'),
        ),
    ]
