# Generated by Django 5.0.2 on 2025-05-01 19:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.PostImage.post_image_upload_to),
        ),
    ]
