# Generated by Django 5.0.2 on 2025-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0006_certificate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExpirence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('location', models.URLField(blank=True)),
                ('technologies', models.ManyToManyField(related_name='all_technologies_workexpirence', to='certificates.technology')),
            ],
        ),
    ]
