# Generated by Django 5.0.2 on 2025-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexpirence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexpirence',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexpirence',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
