# Generated by Django 5.0.2 on 2025-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexpirence', '0002_workexpirence_final_date_workexpirence_initial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpirence',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/workexpirence'),
        ),
    ]
