# Generated by Django 5.0.2 on 2025-05-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='isPortfolio',
            field=models.BooleanField(default=False),
        ),
    ]
